### ISSUE TITLE
Website feedback

### ISSUE THREAD

**Issue by jhellewell14** [epiforecasts/covid#10]
## Methods:

- [x] spacing issues after citations (https://github.com/epiforecasts/covid/commit/4f6be5e9c6f338ba71d26588d8654494ff1e1c72)
- [x] need to space out the equations more (https://github.com/epiforecasts/covid/commit/4f6be5e9c6f338ba71d26588d8654494ff1e1c72)

## Contributors

- [x] Decide upon final organisation of contributors

## Italy

- [x] Fix NAs on Italy map. Partially fixed by changing region_codes.rds but other regions don't seem to return any result, need to check why. (https://github.com/epiforecasts/covid/commit/2af177879c8cab578c179efaa34637ce9c56f000)

## Maps

- [x] Pick better colours to correspond to Increasing, Likely increasing etc. and sync them with all other plots (begun this in a branch)
- [x] Better explanation of why certain locations are NA, state that not enough data/cases etc

## Layout

- [x] Put Figure 1 above the summary table on each region page

**Comment by seabbs** [comment]
Building on this: 

- [ ] Negative doubling times should be changed to cases decreasing (point estimates)

- [ ] Italy map has NA regions -> fix in `EpiNow` but not post-processing region names

**Comment by seabbs** [comment]
Really keen on keeping it being table then figure. Deal-breaker?

**Comment by seabbs** [comment]
Moved NA issue into a meta-thread. Late-night Sam can't fix. Morning Sam may be able to do so rapidly.
