### ISSUE TITLE
National Entries

### ISSUE THREAD

**Issue by sggeris** [epiforecasts/covid#100]
Hello, 

Previously, national data for each countries estimated R-value was available, but now only estimates with sub-national data are showing up. Additionally, under the "global" tab, the map's hover feature is not working properly, as Chile's data will not show up when hovering over any part of the country. This information is crucial to my assessments for work, and any update would be appreciated. 

Thank you, 
Samantha

**Comment by joeHickson** [comment]
Hi Samantha,
You can access the data for Chile on the website by going National -> Americas -> Chile (available here: https://epiforecasts.io/covid/posts/national/chile/ )
I agree it is hard to pick Chile on the map - I tend to find the drop down easiest for all but the largest countries. I'll make sure the feedback gets to the team responsible for the map.
![image](https://user-images.githubusercontent.com/8492240/96845020-240d8a00-1448-11eb-84a3-f470afe665a4.png)

If you need more data for your assessments we do publish our data as raw tables as part of the https://github.com/epiforecasts/covid-rt-estimates project

I hope this helps.

Joe

**Comment by seabbs** [comment]
Hi @sggeris thaks for opening this and sorry you have had issues. 

@hamishgibbs is working on a fix for the popup issues but as @joeHickson suggests accessing the data itself may be helpful as well. 

Please feel free to comment here or elsewhere if this is still an issue.

**Comment by hamishgibbs** [comment]
Thanks Samatha, this issue is open in `rt_vis` (the JavaScript library supporting the site). We will work on getting a fix ASAP!

https://github.com/hamishgibbs/rt_vis/issues/40
