### ISSUE TITLE
Graphs are confusing

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/covid#101]
In particular the combination of shading for confidence interval and shading for strength of likelihood. This makes it hard to tell what is going on - the graph being all one colour (particularly unsure) looks a bit broken and it's hard to identify the difference between Increasing and Likely Increasing and the same will be true of the blue.
![image](https://user-images.githubusercontent.com/8492240/96991343-33600680-1520-11eb-80df-ade36c6ae728.png)

This relates to #82 but is focused on the graph.

I think it may have been amplified by cherry picking graphs out the results but the graph could do with a note about CI on the key and perhaps needs a more significant change of hue with the likelihood so that the saturation change for CI is clearer.

**Comment by gunnarkaestle** [comment]
What about introducing a different pattern for confidence intervals, e.g. for the whiskers a color-white-color-white-stripe pattern, that is easy to discriminate from the high confidence areas?
