### ISSUE TITLE
Estimates for Italy stopped updating on 31/10/2020

### ISSUE THREAD

**Issue by Alem95** [epiforecasts/covid#105]
As you can see from this page https://epiforecasts.io/covid/posts/national/italy/ the covid Rt estimates for Italy have stopped updating on the 31st of October despite the fact that the source https://github.com/pcm-dpc/COVID-19 has been uploading new data everyday

**Comment by seabbs** [comment]
Hi @Alem95, 

Thanks for opening this. Unfortunately, we hit a technical issue at the same time as having a shortage of people power. Hopefully we will have the project back online this week. 

Sam

**Comment by seabbs** [comment]
Hi Alem, 

These publishing problems should hopefully be largely resolved. Thanks again for opening this.
