### ISSUE TITLE
Significant digits in tables

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid#109]
Rather than rounding to X digits it would be good to have X significant digits in the tables, e.g. here the level of precision in case numbers and growth rates implies unrealistic accuracy:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/1156307/101891545-18ae2380-3b9a-11eb-927f-167955d8596e.png">

**Comment by sbfnk** [comment]
i.e. `signif(x, 2)` instead of `round(x, 1)` for all numeric columns.

**Comment by seabbs** [comment]
Done in https://github.com/epiforecasts/EpiNow2/commit/ab3ce630db80b468c3a44289b1fa9f59e13044de

Will come through in new results tomorrow and then the website.

**Comment by seabbs** [comment]
Switching to significant figures everywhere has had some fairly negative consequences in plots made from summary information. 

Rolling back for summary csvs and potentially should consider doing the same for the effective reproduction number in tables (as we using significant figures we would show more information when rt < 1 than when it is > 1).
