### ISSUE TITLE
UK page is not updating automatically

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid#113]
The UK page appears to not be updating automatically with other pages though it does now render interactively. Since I last updated 5 days ago no update has succeeded. I have just run another manual update and found no issue so this could do with having an eye kept on it.

**Comment by seabbs** [comment]
I see, 

```
  |......................                                                |  31%
label: rt-comparison-nations (with options)
List of 6
 $ fig.height: num 12
 $ fig.width : num 14
 $ out.width : chr "95%"
 $ echo      : logi FALSE
 $ message   : logi FALSE
 $ warning   : logi FALSE

Quitting from lines 69-137 (united-kingdom.Rmd)

Warning message:
In .f(.x[[i]], ...) :
  united-kingdom: Error: `:=` can only be used within a quasiquoted argument

                             page
1: _posts/national/united-kingdom
```

When running `bash bin/update_website.sh` and no error when using `rmarkdown::render` in `_posts/national/united-kingdom`.

**Comment by seabbs** [comment]
I assume this is the same issue that was causing it to fail to generate previously but so far I have not been able to debug it.

**Comment by kathsherratt** [comment]
Thanks for flagging, I will continue to keep an eye on the UK updates. 

I can't explain why it would only fail in bash but I'll recheck the code again in case that shows anything.

**Comment by seabbs** [comment]
Still no idea what is causing this issue. I have added a step to the website build process so it explicitly renders the UK page on its own first before doing anything else. Hopefully that will work!

**Comment by seabbs** [comment]
So this looks like its a site wide issue when `data.table` is used in pages (and in particular `:=`) - potentially in combination with `tidyverse` packages. This was highlighted by @sbfnk recent change to force a variable to be a factor across all pages with results in all pages failing to build when run using the scripts in the repo. 

When run interactively all worked as expected and when run from a single render script. Issue only occurs when running multiple renders in a `map` or `future_map` loop - which I assume means it is some kind of scoping issue. 

Currently I have failed to get to the bottom of the cause. The work around is to explicitly render any pages that use `:=` (i.e the UK) and rewrite `force_factor` to not use `data.table`.

**Comment by kathsherratt** [comment]
On Figure 1 / Table 1 of the UK page ("Regional" tab) I can only see 4 of the big regions (South East, South West, UK, Wales, with latest estimate as of 2021-01-16) - we are missing everywhere else.

Still, switching to "Local" shows all the LA estimates for everywhere, and all the big regions are shown in the comparison by data source section (Fig 2+).

At first glance it doesn't seem to be a data problem from a quick `covidregionaldata` check.

**Comment by sbfnk** [comment]
Yes, our colleagues at met office tried a new set up and it failed. They're aware of it so hopefully it won't happen again.

**Comment by seabbs** [comment]
The error is in the estimation pipeline I think. It is probably related to the switch over from the single box to using the batch approach that @joeHickson  and @ChrisPaulBennett have been doing. If that is the case it should resolve its self tomorrow. If its something else that will investigate tomorrow.

**Comment by sbfnk** [comment]
Issue arose here which is in batch commit https://github.com/epiforecasts/covid-rt-estimates/commit/cccedeae51a45744c6ff0a3cc4e3247d0eaf7bb1
