### ISSUE TITLE
Sorting on doubling/halving time isn't using numeric sort

### ISSUE THREAD

**Issue by mfranklin1** [epiforecasts/covid#121]
Eg https://epiforecasts.io/covid/posts/national/united-states/

Sort on doubling/halving time and you get 

Texas | 21099 (14763 -- 29059) | Stable | 1 (0.93 -- 1.1) | 0.0021 (-0.02 -- 0.021) | 320 (34 -- -34)
-- | -- | -- | -- | -- | --
Oregon | 881 (479 -- 2369) | Likely increasing | 1.1 (0.87 -- 1.7) | 0.028 (-0.037 -- 0.18) | 25 (3.9 -- -19)
Kansas | 1984 (568 -- 4629) | Likely decreasing | 0.97 (0.72 -- 1.1) | -0.0072 (-0.081 -- 0.03) | -96 (23 -- -8.6)
Iowa | 791 (335 -- 2094) | Stable | 0.97 (0.68 -- 1.4) | -0.0082 (-0.092 -- 0.12) | -85 (5.9 -- -7.5)
California | 6292 (3157 -- 11014) | Decreasing | 0.71 (0.52 -- 0.9) | -0.082 (-0.14 -- -0.028) | -8.4 (-25 -- -4.9)
Alabama | 2412 (1672 -- 3611) | Likely decreasing | 0.97 (0.87 -- 1.1) | -0.0095 (-0.038 -- 0.027) | -73 (26 -- -18)
Wyoming | 48 (16 -- 125) | Decreasing | 0.68 (0.43 -- 0.94) | -0.092 (-0.18 -- -0.016) | -7.5 (-44 -- -4)
North Carolina | 5303 (2915 -- 9004) | Likely decreasing | 0.95 (0.81 -- 1.1) | -0.013 (-0.054 -- 0.021) | -54 (33 -- -13)
Northern Mariana Islands | 0 (0 -- 1) | Likely decreasing | 0.95 (0.48 -- 1.3) | -0.013 (-0.15 -- 0.085) | -52 (8.2 -- -4.5)
Colorado | 1098 (628 -- 2347) | Likely decreasing | 0.95 (0.76 -- 1.3) | -0.014 (-0.07 -- 0.084) | -50 (8.2 -- -9.9)

Note sure what that's sorting on but putting -8.4 (california) between -85 (Iowa) and -73 (Alabama) would appear to be wrong to me.

**Comment by fjarlq** [comment]
This problem also happens when sorting by new confirmed cases.
