### ISSUE TITLE
Missouri estimates are clearly incorrect (doubling time of 0.46 days)

### ISSUE THREAD

**Issue by dirkks** [epiforecasts/covid#128]
As of the creation of this issue, the Missouri page https://epiforecasts.io/covid/posts/subnational/united-states/missouri/ data looks like this, which is clearly incorrect, presumably a data import issue of some kind:

  | Estimate
-- | --
New confirmed cases by infection date | 1136600 (581792 – 1813090)
Expected change in daily cases | Increasing
Effective reproduction no. | 9.3 (7.3 – 9.9)
Rate of growth | 1.5 (1.2 – 1.7)
Doubling/halving time (days) | 0.46 (0.4 – 0.57)

**Comment by seabbs** [comment]
I see a reporting spike of 40,000 early in March which likely drove this issue.
