### ISSUE TITLE
Missouri numbers out of wack

### ISSUE THREAD

**Issue by ninjubohra** [epiforecasts/covid#129]
The numbers for Missouri all the sudden went very very high.  For the last 2 days it has reported over 1 million new cases which is not right.

Just thought you'd want to know

**Comment by seabbs** [comment]
Thanks for flagging. Unfortunately reporting changes are very hard for us to deal with as data providers often provide little information (and none in an automated fashion). For this reason it is best to view these results with a sceptical eye.
