### ISSUE TITLE
trend categories: NA vs unsure vs ...

### ISSUE THREAD

**Issue by pearsonca** [epiforecasts/covid#13]
For color / labelling scheme:
 - [x] is there a likely decreasing / decreasing category? if so, should show even if there aren't any examples currently
- [x] there's no apparent gradient currently from increasing -> likely increasing -> unsure, but there is conceptually; worth having a gradient in the color scheme?
 - [x] the NAs need to be more distinct from other colors
 - [x] the NAs could use a more useful label. Seems like there's two flavors? No reported cases, and not-yet-at-100 cases threshold?

**Comment by seabbs** [comment]
Ty for the comments - all good feedback. Will look at changing tomorrow.

**Comment by seabbs** [comment]
I moved your comments into meta-threads as they captured some concerns others were also having. Thanks again.

**Comment by seabbs** [comment]
Closing as resolved or categorized for future work.
