### ISSUE TITLE
Diagram style: ummary of latest reproduction number and confirmed case count estimates by date of infection

### ISSUE THREAD

**Issue by gunnarkaestle** [epiforecasts/covid#130]
Regarding figure 1 in https://epiforecasts.io/covid/posts/global/
there is a small reading issue for this diagram.

It is a long graph consisting of two rows with bar charts, and one row with vertically printed country names. To match the data with the countries, it is important that the mapping of the country to the to data rows can easily be done. While there are markers on the x-axises (ticks) for the two bar charts which are aligned to the middle of each bar, the lettering below is shifted by half a bar with.

Thus, when you try to aim in blow up mode e.g. with the border of the screen which bar belongs to which contry, you have a multiple choice as basically two country names do match similarly (spoiler alert: it is the right one). Therefore, to avoid confusion, it would be helpful to place the legend in the 3rd row a little bit more to the left, e.g. by half a bar with.

**Comment by gunnarkaestle** [comment]
Here you can see the shift of half the width of a single bar between the legend on the bottom and the two rows of bars indicating the number of infections and the R values.
![2021-04-24_epiforecasts_global_index](https://user-images.githubusercontent.com/15989715/115973007-38932200-a552-11eb-87d1-dde9d8246417.png)

**Comment by seabbs** [comment]
Yes I agree it makes sense to resolve this. Really an issue for EpiNow2 I think so closing here.
