### ISSUE TITLE
Alabama Data corrupted by backlog data dump.

### ISSUE THREAD

**Issue by JeepGeek** [epiforecasts/covid#132]
https://covid19.alabama.gov/

mportant Notice (03/17/21)

 

The Alabama Department of Public Health (ADPH) processed a backlog of 201 cases on 03/17/21. These will be classified as confirmed and probable COVID-19 cases reported on 03/16/21 even though the tests were performed on during October 1, 2020 through March 8, 2021.

 

For information regarding daily numbers and the 7-day moving average of cases by infectious date, see Tab 7A. Information on Tab 7A visualizes cases by date of infection rather than date reported.

 

All laboratories are required by law to report all results (including positive and negative tests) for SARS-CoV-2 to ADPH. Delays in reporting by required reporters is not within control of ADPH.

 

Important Notice (03/15/21)

 

The Alabama Department of Public Health (ADPH) processed a backlog of 4007 cases on 03/14/21. These will be classified as confirmed and probable COVID-19 cases reported on 03/15/21 even though the tests were performed on during October 1, 2020 through January 1, 2021.

 

For information regarding daily numbers and the 7-day moving average of cases by infectious date, see Tab 7A. Information on Tab 7A visualizes cases by date of infection rather than date reported.

 

All laboratories are required by law to report all results (including positive and negative tests) for SARS-CoV-2 to ADPH. Delays in reporting by required reporters is not within control of ADPH.

 

Important Notice (03/04/21)

 

The Alabama Department of Public Health (ADPH) processed a backlog of 2114 positive PCR results from a facility on 03/02/21 and 346 positive PCR results from the same facility on 03/03/21. These will be classified as confirmed COVID-19 cases reported on 03/03/21 and 03/04/21 even though the tests were performed since May 2020.

 

For information regarding daily numbers and the 7-day moving average of cases by infectious date, see Tab 7A. Information on Tab 7A visualizes cases by date of infection rather than date reported.

**Comment by seabbs** [comment]
Thanks for flagging and sorry for not getting back to you earlier. These issues are difficult to account for if not adjusted in our downstream data sets and hence results best read with a critical eye for data issues.

**Comment by JeepGeek** [comment]
And that is what I do.. I still disagree with the ADPH #s for Active cases… There is no way possible that there are 183k active cases in this state. And don’t get me started on the delta between ADPH and HHS Hospitalization numbers, I just cannot get anyone to pick up the phone or email.

Thank you again for your contribution.

Russ
