### ISSUE TITLE
BC, Canada, number in error

### ISSUE THREAD

**Issue by shanajohnstone** [epiforecasts/covid#133]
March 22-23, 2021, the number for BC was recorded as 

“New confirmed cases by infection date | 5033 (1612 – 21955)”
-- | --

But instead of 5033 it should be 600 or so.

**Comment by seabbs** [comment]
Thanks for opening this. Two points. 1. This is an estimate by date of infection and therefore in an increasing epidemic numbers will be higher than observed. 2. Looking at BC I see some reporting issues that like have driven some spurious results.
