### ISSUE TITLE
Links to subnational united stats (California) no longer working

### ISSUE THREAD

**Issue by criccomini** [epiforecasts/covid#141]
I've been watching:

https://epiforecasts.io/covid/posts/subnational/united-states/california

This link 404's now.

It's still in use on this page:

https://epiforecasts.io/covid/posts/national/united-states/

**Comment by PointMeAtTheDawn** [comment]
Appears to have similar behavior as https://github.com/epiforecasts/covid/issues/140

**Comment by mcovington** [comment]
Georgia's link is now a 404 also.  Previously, it stopped updating for a couple of days.

**Comment by kriegsman** [comment]
Similarly, 404 for Massachusetts. Presumably all the same problem so I’m commenting here instead of opening a new Issue. https://epiforecasts.io/covid/posts/subnational/united-states/massachusetts/

**Comment by seabbs** [comment]
Thanks all for flagging and apologies for the outage. State pages should now be back online. 

The server I use to update the site ran out of space whilst I was on leave but that should now be resolved. 

For interest the raw results are output here: https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/united-states/cases/summary

These run on a different system to the website and so are less likely to have publishing issues.

**Comment by kriegsman** [comment]
Thanks so much for all your work during this whole mess.  It's been a real source of clarity and understanding.
