### ISSUE TITLE
Martinique

### ISSUE THREAD

**Issue by gunnarkaestle** [epiforecasts/covid#143]
Data source for Martinique infections should be checked.

Martinique
new confirmed cases | 15395 (1707 -- 139044) 
expected change | Likely increasing
effective reproduction | 1.4 (0.63 -- 2.1)
rate of growth | 0.1 (-0.11 -- 0.28) 
doubling time (days) | 6.7 (2.5 -- -6.5)

(Global Table showing 111 to 120 of 202 entries as of the 2021-04-26)

see also https://www.worldometers.info/coronavirus/country/martinique/
Total Coronavirus Cases in Martinique: ~10k
Daily new cases (7 d average): ca 100

It is a small island and it is #7 in the global list of countries, sorted by registered infection cases.
(Figure 1: Confirmed cases with date of infection on the 2021-04-26 and the time-varying estimate of the effective reproduction number)

**Comment by sbfnk** [comment]
This seems fine - probably a transient issue due to rapid increase from a very low level (a known issue with the underlying model).
