### ISSUE TITLE
India: Subnational estimates are missing for Gujarat 

### ISSUE THREAD

**Issue by mv2405** [epiforecasts/covid#146]
Dear team, 

I would appreciate it if you could update CSV to include Gujarat and Madhya Pradesh estimates - it is available on the reports:
https://epiforecasts.io/covid/posts/subnational/india/gujarat/
https://epiforecasts.io/covid/posts/subnational/india/madhya-pradesh/

https://raw.githubusercontent.com/epiforecasts/covid-rt-estimates/master/subnational/india/cases/summary/rt.csv

Thank you very much in advance.

**Comment by sbfnk** [comment]
These seem to be there now. If regions are ever missing it might be because a model run failed, e.g. due to data anomalies. In that case the last available estimate would still be shown on the web site but it would not appear in the csv.
