### ISSUE TITLE
Qatar data is outdated

### ISSUE THREAD

**Issue by wodi-02** [epiforecasts/covid#147]
Greetings,

Thank you for the wonderful tools you've created, it shows interesting data and trends that is helpful.

I've noticed that Qatar data was not updated since March. Hopefully it's fixable.

https://epiforecasts.io/covid/posts/national/qatar/

**Comment by seabbs** [comment]
Thanks for flagging this. Now resolved. 

Just a note that the model is designed to work with real infectious disease data so data streams that have non-realistic dynamics can cause issues (but as long as the bias is constant the impact on Rt estimates should be small but will introduce lag_

**Comment by sbfnk** [comment]
This seems fixed now.
