### ISSUE TITLE
Medium term changes

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid#15]
- [ ] Add a second global map that is split by continent (@samclifford).
- [x] Make NAs be informative (can be short term if someone has a speedy fix @jhellewell14 @pearsonca). Flagged this in caption, limitations, and methods for now (3f63772
)
- [ ] Figure interactivity
- [x] Consider fixed x-axis in comparative plots
- [ ] Add two dimensions to plots with hatching and colours for certainty and scale
- [x] Split nowcast results from website to make more modular. Keep nowcast results that are out of data off GitHub in deep store to keep the git repo relatively light weight. Do this by moving now-casts into a new repo covid-nowcasts and using a sub module. Regular git history purges and archives to dropbox for historic results.
- [ ] Show report delay as a plot in the methods

**Comment by samclifford** [comment]
Plotly dropdown menu that defaults to world but allows you to select a specific continent? Leaflet that gives you ability to scroll and zoom as desired with mouse over boxes containing CIs?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
