### ISSUE TITLE
Alabama - backlog of COVID19 cases in reporting since May 28, 2021

### ISSUE THREAD

**Issue by SavvyDee** [epiforecasts/covid#150]
Since May 28, 2021, AL Dept of Public Health has reported an additional 3.440 COVID-19 cases to its cumulative total - HOWEVER, as you can see in the chart pasted below, only 1,925 of those cases (55% of the total) have a "date of infectiousness" on or after February 25, 2021 (105 days before today) - that means nearly half of the "new" cases reported so far in June WERE MORE THAN 100 DAYS OLD WHEN REPORTED, so they are certainly not reflective of the "CURRENT" situation in Alabama.  Furthermore, only 887 of those cases have a date of infectiousness in June 2021.  Per the ADPH Dashboard, the current 14-day case count is 1,765 -- back on June 1, 2021, the 14-day case count was 2,190....clearly, cases in Alabama are decreasing, not remaining "stable" as indicated on your website.  

ADPH has consistently had an issue with reporting older cases (and deaths) -- not necessarily because of an issue at the Dept, but rather because the required reporters often report well outside of what one would consider a reasonable reporting period.  

Please review the information at Tab 7 of ADPH's dashboard (https://alpublichealth.maps.arcgis.com/apps/MapSeries/index.html?appid=d84846411471404c83313bfe7ab2a367) to see that the cases as well as the 3/7/14 day averages are clearly declining.

DATE | CHANGE 5/28 to 6/9 | ADPH TAB 7 CASES 6/9 | ADPH TAB 7 CASES 5/28/2021
8-Jun | 27 | 27 | 0
7-Jun | 111 | 111 | 0
6-Jun | 77 | 77 | 0
5-Jun | 68 | 68 | 0
4-Jun | 100 | 100 | 0
3-Jun | 136 | 136 | 0
2-Jun | 175 | 175 | 0
1-Jun | 193 | 193 | 0
31-May | 109 | 109 | 0
30-May | 122 | 122 | 0
29-May | 110 | 110 | 0
28-May | 158 | 158 | 0
27-May | 118 | 169 | 51
26-May | 76 | 210 | 134
25-May | 37 | 187 | 150
24-May | 36 | 260 | 224
23-May | 27 | 155 | 128
22-May | 42 | 187 | 145
21-May | 38 | 276 | 238
20-May | 15 | 252 | 237
19-May | 17 | 256 | 239
18-May | 12 | 282 | 270
17-May | 24 | 362 | 338
16-May | -1 | 206 | 207
15-May | 2 | 205 | 203
14-May | 3 | 278 | 275
13-May | 13 | 285 | 272
12-May | 5 | 357 | 352
11-May | 1 | 317 | 316
10-May | 6 | 394 | 388
9-May | 10 | 210 | 200
8-May | 4 | 231 | 227
7-May | 0 | 297 | 297
6-May | 3 | 341 | 338
5-May | -2 | 397 | 399
4-May | 3 | 367 | 364
3-May | 3 | 482 | 479
2-May | 0 | 279 | 279
1-May | 2 | 278 | 276
30-Apr | 5 | 338 | 333
29-Apr | 2 | 373 | 371
28-Apr | 3 | 453 | 450
27-Apr | 4 | 439 | 435
26-Apr | 7 | 496 | 489
25-Apr | 3 | 274 | 271
24-Apr | 3 | 273 | 270
23-Apr | 0 | 393 | 393
22-Apr | 1 | 378 | 377
21-Apr | -1 | 617 | 618
20-Apr | 0 | 450 | 450
19-Apr | 0 | 550 | 550
18-Apr | 0 | 320 | 320
17-Apr | 0 | 275 | 275
16-Apr | 0 | 419 | 419
15-Apr | -2 | 409 | 411
14-Apr | 0 | 444 | 444
13-Apr | 0 | 482 | 482
12-Apr | 0 | 570 | 570
11-Apr | 0 | 290 | 290
10-Apr | 0 | 313 | 313
9-Apr | -1 | 430 | 431
8-Apr | 0 | 403 | 403
7-Apr | 0 | 440 | 440
6-Apr | 0 | 468 | 468
5-Apr | 0 | 562 | 562
4-Apr | 0 | 242 | 242
3-Apr | 0 | 251 | 251
2-Apr | -1 | 367 | 368
1-Apr | -1 | 399 | 400
31-Mar | 0 | 343 | 343
30-Mar | 1 | 405 | 404
29-Mar | 1 | 462 | 461
28-Mar | 0 | 271 | 271
27-Mar | 0 | 288 | 288
26-Mar | 1 | 359 | 358
25-Mar | -1 | 313 | 314
24-Mar | -3 | 431 | 434
23-Mar | 0 | 440 | 440
22-Mar | -2 | 541 | 543
21-Mar | -2 | 277 | 279
20-Mar | 1 | 333 | 332
19-Mar | -1 | 375 | 376
18-Mar | 0 | 473 | 473
17-Mar | 1 | 402 | 401
16-Mar | 0 | 455 | 455
15-Mar | 0 | 601 | 601
14-Mar | 2 | 300 | 298
13-Mar | 1 | 293 | 292
12-Mar | 0 | 473 | 473
11-Mar | 1 | 477 | 476
10-Mar | 1 | 480 | 479
9-Mar | 2 | 535 | 533
8-Mar | 1 | 537 | 536
7-Mar | 1 | 345 | 344
6-Mar | 0 | 361 | 361
5-Mar | 6 | 511 | 505
4-Mar | 0 | 502 | 502
3-Mar | 1 | 577 | 576
2-Mar | 0 | 570 | 570
1-Mar | 3 | 885 | 882
28-Feb | 1 | 493 | 492
27-Feb | 2 | 438 | 436
26-Feb | 1 | 680 | 679
25-Feb | 4 | 767 | 763
TOTAL INCREASE IN CASES | 1,925 |

**Comment by seabbs** [comment]
Thanks for flagging this. It looks like Alabama changed its within week reporting pattern causing some models issues. These look to now be resolved and the data/Rt estimate seem in line so closing this issue.
