### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by mcovington** [epiforecasts/covid#162]
As has happened before, https://epiforecasts.io/covid/posts/subnational/united-states/georgia/ is not updating.

Georgia DPH recently stopped issuing reports on weekends, but I thought you had adapted to that already.

**Comment by sbfnk** [comment]
It seems to be up-to-date -- note that we cut off the last 4 days of data to deal with data delay/revision errors.

**Comment by sbfnk** [comment]
This has been fixed.
