### ISSUE TITLE
GCC Countries Summary not Updated

### ISSUE THREAD

**Issue by josebsalazar** [epiforecasts/covid#163]
For the GCC countries of Bahrain, Kuwait, Saudi Arabia, UAE, and Oman, the data indicates data available to 2021-07-24, but the summary estimate shows a week behind of 2101-07-15..

Many thanks.

**Comment by sbfnk** [comment]
Thanks for flagging. Related #164.

**Comment by sbfnk** [comment]
This has been fixed.

**Comment by josebsalazar** [comment]
Noted and thanks. 


Sent from Yahoo Mail for iPhone


On Friday, July 30, 2021, 3:25 PM, Sebastian Funk ***@***.***> wrote:




This has been fixed.
