### ISSUE TITLE
Estimates not being updated

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid#164]
Estimates are currently not being updated, possibly due to a recent update in the underlying infrastructure.

cc @joeHickson.

**Comment by joeHickson** [comment]
@sbfnk github credentials issue - details in an email and  the first 7 datasets are in flight.

**Comment by sbfnk** [comment]
Thanks, @joeHickson. I'll keep this open until the web site is updated later today, as a reference in case people are looking here for info on why the web site is out of date.

**Comment by sbfnk** [comment]
All up-to-date again on the website and associated github repo.
