### ISSUE TITLE
Recurrent update of paper.docx/paper.pdf

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid#165]
@seabbs are lines 3-7 needed here?
https://github.com/epiforecasts/covid/blob/be50d502ebe68800c19113378192de1fe94b2a68/bin/update_github.sh#L3
There shouldn't be anything to commit from master, and any changes to the paper, text, markdown etc. would be added locally.

**Comment by seabbs** [comment]
Hmm I think not if not updating the paper etc which I agree should happen somewhere else.
