### ISSUE TITLE
Increase smoothing of data used to calculate R

### ISSUE THREAD

**Issue by dxgldotorg** [epiforecasts/covid#169]
Since many states are not posting data as regularly as before, this is causing the calculated R to fluctuate wildly.  If the data is smoothed more, this could decrease the fluctuations.

**Comment by sbfnk** [comment]
Our model has a estimates a day-of-the-week reporting effect so if countries don't publish data for certain days it should not affect our estimates. The only exception is when the reporting pattern changes, see e.g. https://github.com/epiforecasts/covid/issues/171
