### ISSUE TITLE
Infinite doubling times not being properly caught in `EpiNow`

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid#18]
Changes upstream mean that infinite doubling times are not being properly caught. Review and fix.

**Comment by gunnarkaestle** [comment]
Isn't a negative doubling time just a half-time?
f(t) = f_0 * e^(ln(R)*t/T)

**Comment by AndreaPi** [comment]
@gunnarkaestle sure, but you cannot have a CI whose lower bound is positive, in that case. In other words, you cannot have something like this:

![image](https://user-images.githubusercontent.com/8233615/80005271-a4682800-84c3-11ea-9c32-f45aaa60013e.png)

**Comment by seabbs** [comment]
Settled on adding no filter to the CIs this means doubling time can now be positive/negative and has been renamed doubling/halving. Think this gives maximum info even if it makes interpretation a little tricky.
