### ISSUE TITLE
Updated national summary

### ISSUE THREAD

**Issue by Pookiedr** [epiforecasts/covid#180]
Your national summary has not updated in over a week. Are you no longer tracking?

**Comment by seabbs** [comment]
Yes, currently the website is down as we have lost our Azure sponsorship and hence do not have the compute required to update. It looks like this is being resolved though so updates should resume in the next week hopefully.

**Comment by Pookiedr** [comment]
Thank you for the information. Good luck.

**Comment by sbfnk** [comment]
Problems with our backend have been resolved, and estimates are up-to-date.
