### ISSUE TITLE
No Updates?!?

### ISSUE THREAD

**Issue by khenault** [epiforecasts/covid#181]
The web page hasn't been updated since 10/23?  i find the page really useful, and miss the regular updates at https://epiforecasts.io/covid/posts/national/united-states/.

**Comment by adam-beck** [comment]
See https://github.com/epiforecasts/covid/issues/180#issuecomment-956501092

**Comment by aaeegg** [comment]
Epiforecasts has left the building. Try these sites:

https://covidestim.org/ (click on "Effective reproduction number")
https://ca-covid-r.info/ (click on "US States/Territories" and scroll down)
https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Reproduction+rate&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=USA~GBR~CAN~DEU~ITA~IND

**Comment by sbfnk** [comment]
Duplicate of #180

**Comment by sbfnk** [comment]
Problems with our backend have been resolved, and estimates are up-to-date.
