### ISSUE TITLE
missing Brazil subnational Rt estimates

### ISSUE THREAD

**Issue by cwhittaker1000** [epiforecasts/covid#183]
Thanks for the incredible resource you've put together! I'm interested in the sub-national Rt estimates for Brazil and was wondering how best to access them? (I'm after state-specific estimates of Rt over time from the beginning of the country's epidemic)

I went to https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DNUA7W which appeared to be the most recent version but there don't appear to be any files associated with that entry. That entry seemed to be from May 2021 and so I was also wondering whether more recent updates were available (https://epiforecasts.io/covid/posts/national/brazil/ seemed to suggest you were still doing regular updates). 

Thanks in advance and hope that makes sense (if unclear let me know and I'll try and clarify further)! :)

**Comment by sbfnk** [comment]
Hi, sorry it isn't clear where to get them, we'll need to update some links. Daily updated estimates are at https://github.com/epiforecasts/covid-rt-estimates/tree/master/subnational/brazil/cases/summary

**Comment by cwhittaker1000** [comment]
Amazing, thanks very much @sbfnk - a quick follow-up question (and apologies if I'm still missing something) - the estimates appear to start from the beginning of August 2021. I was hoping to get the Rt estimates spanning the entirety of the country's epidemic (at the state-level) - are those available anywhere?

**Comment by sbfnk** [comment]
Not at the moment - this is [work in progress](https://github.com/epiforecasts/covid-rt-estimates/issues/15). As a quick hack in the interim you could piece together an approximate long time series (starting in June 2020 - we don't have any earlier estimates using current methodology) from the individual commits, see
https://gist.github.com/sbfnk/fbec24bb23259b7823281621920e0e32

**Comment by cwhittaker1000** [comment]
Super helpful, thanks so much @sbfnk, I'll have a play and see how I get on!
