### ISSUE TITLE
Aggregation issues? 

### ISSUE THREAD

**Issue by gunnarkaestle** [epiforecasts/covid#184]
Regarding the presentation of the results for Germany (as of 2021-11-17) there is a discrepancy between the whole country and the federal states. The effective reproduction number is 1.1 and as shown in figure 1c since weeks way beyond the 1,0.  But the federal states are generally assessed to be below 1.0 see Table 2.

![2021-11-27T09 56 45A_DE_Summary](https://user-images.githubusercontent.com/15989715/143677531-609e22e7-8615-4afd-b6ac-f79f4de1157e.png)

![2021-11-27T09 56 12A_DE_National_Subsets](https://user-images.githubusercontent.com/15989715/143677538-df812d2d-1042-4b2d-b576-cf3d1faba0ce.png)

I believe there is something wrong with the federal states, as indeed the case numbers in Germany are going up and are now in the range of 50.000 registered infections per day. But it is impossible that the overall entity says "I am growing" while the subsets say "We are shrinking".

**Comment by sbfnk** [comment]
Thanks for raising this - your comment unearthed an issue in our processing of the subnational data from Germany. This has now been fixed and the estimates should be consistent.
