### ISSUE TITLE
Iowa and Florida data (United States, Subnational)  OBVIOUSLY WRONG.

### ISSUE THREAD

**Issue by dksia54** [epiforecasts/covid#185]
Hello --

I have to question if any of your members who are responsible for the daily upkeep of your site ever bother to look at the data and simply ask themselves if the data is correct.

Today, both Iowa and Florida data are quite obviously seriously screwed up.  If you do nothing else, at least put some form of quality control into your data entry.  The site is good, but with inconsistent, incorrect data, it is not a reliable indicator of the progress of Covid.

**Comment by sbfnk** [comment]
Thank your message. We do not have the capacity to investigate every individual daily estimate, so we're relying on the kind contributions of the likes of yourself to alert us when there is an issue.

The data from many states in the US is subject to strong reporting artefacts, which appear to have been exacerbated by the holidays to a degree that it threw our model in the two instances you mentioned. We've removed these for the time being, and will reinstate them in a few days when things have normalised.
