### ISSUE TITLE
estimates before mid August

### ISSUE THREAD

**Issue by itastelikesunshinedust** [epiforecasts/covid#188]
Thanks for your great work. 
I was wondering if a dataset/.csv with national effective R estimates before mid August (2021) is available for download somewhere? Thanks!

**Comment by sbfnk** [comment]
There's not a single location to download long-term estimates but if you're using R you could try and stitch them together from the estimates at various times by installing the `gh` package and using the code at https://gist.github.com/sbfnk/d2900c745312219e3e48e08adde47cde doing something like
```r
source("https://gist.githubusercontent.com/sbfnk/d2900c745312219e3e48e08adde47cde/raw/c98fbdd738eafa71af12d05af0d3e068cf5b607b/get_covid19_nowcasts.r")
rt <- get_covid19_nowcasts()
```
