### ISSUE TITLE
Once again, UNBELIEVABLE data.  Iowa, in the United States, again!!!! Seriously???

### ISSUE THREAD

**Issue by dksia54** [epiforecasts/covid#189]
Once again, you have screwed up the data for Iowa in the United States.  Your data shows more new cases in the state than there are residents.

Is ANYONE in your group going to actually decide to bounds check your data before you publish it???

Please!!! Fix your data, and for God's sake, check it before you post. Your site is unreliable and cannot be trusted.

Dave Shema

**Comment by sbfnk** [comment]
As explained before, the site is run on automatic updates and relies on the data that is pulled from various sources. The reporting pattern in Iowa recently changed in unpredictable ways which threw the model. For more detail, please consult the [Methods](https://epiforecasts.io/covid/methods.html) section on the web site, and especially the limitations noted there.

Whilst constructive criticism is very much welcomed (and needed), the tone of these comments is not. Please study our [code of conduct](https://github.com/epiforecasts/EpiNow2/blob/master/CODE_OF_CONDUCT.md) before making any further contributions.
