### ISSUE TITLE
Nick comments

### ISSUE THREAD

**Issue by nicholasdavies** [epiforecasts/covid#21]
This looks great. 

- [x] Comments: The ribbons showing cases by date of infection are beautiful but to me are a little tricky to interpret. I hate to say this, but would this maybe be clearer as a geom_pointrange (with a thicker line for 50% CrI?) 

- [x] The title "Summary of latest reproduction number and case count estimates by date of infection" to me was confusing as the plot is not by date. 

- [x] Can there be more detail on the difference between wide CrI and the measure of uncertainty that gets reflected as translucency? 

- [x] Can you show distributions that go into estimating e.g. time between infection and reporting? 

-  [x] Can I ask about the doubling times which often have an upper bound of infinity, and for which the point estimate sometimes is not within the uncertainty range (e.g. -100 (14 – Inf) for Italy)?

**Comment by seabbs** [comment]
Thanks for the comments Nick. 

Report delay. estimated on the fly using the data sources supplied. So 1.) changes and 2.) fully based on data that is linked. Could be a good idea to plot this later though. 

Doubling times: Yup this is a weird exception handler  basically. Doubling times that are inf or negative should be being caught and made into cases decreasing but this is not currently happening. Investigating.

Translucency and CI uncertainty. Think this is covered in the methods but if not happy to look at again. 

So the summary plot has the latest estimates by date of infection i.e when it says its for the 29th its by date of infection. Looking at clarifying. 

I think a pointrange will start looking incredibly messy with the observed data plotted over it. Will explore more in later versions.
