### ISSUE TITLE
Brazilian data adm level 1

### ISSUE THREAD

**Issue by lsbastos** [epiforecasts/covid#24]
Hi,

I have been working in a Brazilian task force for covd-19. 

Would you guys be interested to add Brazilian data at subnational level (adm 1)? I could help point out where the data is and help with translation if needed.

Cheers,
Leo

**Comment by seabbs** [comment]
Hi Leo, 

Sorry for the lack of response on this. 

We have been reporting state-level estimates for a while using data linked up [here](https://github.com/epiforecasts/covidregionaldata) but would really appreciate any other contributions.
