### ISSUE TITLE
Remove file LICENSE as there is also LICENSE.md

### ISSUE THREAD

**Issue by tanius** [epiforecasts/covid#30]
I had a slight confusion when trying to find the licence of this repo: the top-right link "View License" on https://github.com/epiforecasts/covid points to file `LICENSE`, which appears to say that it's a normal proprietary software:

```
YEAR: 2020
COPYRIGHT HOLDER: Epiforecasts
```

However then I found `LICENSE.md`, which states it's open source software under the MIT license. Which is great :slightly_smiling_face: The redundant and incomplete / confusing file `LICENSE` can probably be simply deleted. Github will then automatically pick up `LICENSE.md` for the licensing information.

**Comment by seabbs** [comment]
Thanks - sorted!
