### ISSUE TITLE
Netherlands was dropped from the most recent analysis run ?

### ISSUE THREAD

**Issue by HenkPoley** [epiforecasts/covid#31]
It is missing with the 'estimates as of the 2020-03-29' / 'Using data available up to the: 2020-04-08' run. 

But was available with the 'up to 2020-04-03(?)' run.

**Comment by HenkPoley** [comment]
It looks like the images are still being generated: https://github.com/epiforecasts/covid-global/tree/master/national/Netherlands

**Comment by seabbs** [comment]
Very very odd. It looks like estimates are back as of todays build (https://epiforecasts.io/covid/posts/national/netherlands/). 

Thanks for flagging it looks like we have sporadic page build failures - will investigate.

**Comment by seabbs** [comment]
Closing this as set up a second issue as this appears to be a wider problem. Thanks again for flagging.
