### ISSUE TITLE
German region map

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid#34]
It looks like German regions are now not mapping correctly. This may be a change in region name processing or maybe a problem higher up the tool chain (`NCoVUtils`).

**Comment by gunnarkaestle** [comment]
@seabbs : As today, there is no colour allocation in 6 federal states:
- Schleswig-Holstein
- Mecklenburg-Vorpommern
- Saxony-Anhalt
- North Rhine-Westfalia
- Rhineland-Palatinate 
- Baden-Wurttemberg

**Comment by seabbs** [comment]
Thanks for flagging and sorry for the lack of response. Should have a resolution soon.

**Comment by seabbs** [comment]
Should be fixed in latest update - thanks again for flagging
