### ISSUE TITLE
DE map for reproduction number

### ISSUE THREAD

**Issue by gunnarkaestle** [epiforecasts/covid#35]
The map in Figure 1 https://epiforecasts.io/covid/posts/national/germany/ does not fit to the classifications given in figure 4 / table 2.

**Comment by seabbs** [comment]
Thanks for flagging this. It looks like there has been a map/data change. Will investigate and fix. Note that our source for German regional data has not updated since the 10th - we are also investigating this.

**Comment by gunnarkaestle** [comment]
Such a growth map (R) or reactivity map (rho = ln(R)) would be great, even for a smaller granularity. In Germany, there is in principle country-specific data available, see the activity map. https://twitter.com/gunnar_kaestle/status/1249348987414548480 but this is important for any other subnational representation of the local effective reproduction number.

But for the R map (or ln(R) map) I would recommend to use another colour scheme.
- violet
- dark blue (decrease)
- light blue
- green (indifferent)
- yellow
- orange (increase)
- red

Blueish usually means "cooling down", whereas yellow/red means "heating up".

I believe it is important to measure the effect of different NPI measures, and in reactor physics, you just call it the reactivity coefficient ξ =  dρ/dx. A map on the reactivity ln(R) [ln(R) has an additive characteristic] will probably help to coordinate NPIs in a sense to add negative reactivity when and where needed (cf. injection of a control rod in nuclear chain reactions). If you can see that the growth factor R already increases, you don't have to wait until you see a significant rise in the incidence.

**Comment by seabbs** [comment]
This is a good idea - reviewing. Thanks for flagging.

**Comment by gunnarkaestle** [comment]
Thanks for the update of the colour scheme. The maps are much more easily and intuitively readable now. Nevertheless, I still feel that the middle option "unsecure" in dark grey needs some improvement, both in wording and in colour choice.

First, on the wording: "unsecure" implies that the result of the calculation is unsecure, meaning low confidence on the outcome. This is not the case. There is an estimated value, plus minus the confidence interval. If this estimated value is high, then it is labelled "increasing". If it is quite low the label is "decreasing", and if it is slightly above or below 1 so that the confidence interval reaches above or below criticality, the then label has an added "likely". But don't call something "unsure" if you are pretty sure that the R value is around 1 with a very narrow confidence interval, meaning that the new cases number will remain pretty constant. Therefore, I would rather call this category "indifferent", "stationary" or "stable" or any other adjective that indicates a firm horizontally trajectory.

About the colour choice: There are two greys used in the maps. (BYT: What is about adding a map not only to the global and subnational R estimation results, but also of each continent in the "national" category?) The dark grey is explained in the legend, whereas the light gray has non. This may be confusion, so it is recommend to add somewhere an explanation what light green means.

But back to the dark grey: it does not fit perfectly between the light orange and the light blue, as it has a more intense impression (the L value is smaller), meaning that the dark grey optically sticks out of the neighbouring system states, which it should not. Therefore I do recommend to use the light grey instead for the R=~1 representation. Alternatively, we can go back to the rainbow approach and use a light green for the middle colour - this also eliminates the (minor) issue of using two grey hues.

**Comment by seabbs** [comment]
Thanks for this, 

We have some interactive visualizations coming so that will include a range of different maps so closing this for now (see here:https://hamishgibbs.github.io/rt_vis/)
