### ISSUE TITLE
sortable tables

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid#39]
It would be nice if the tables had sortable headings, e.g. using https://rstudio.github.io/DT/

**Comment by sbfnk** [comment]
Or as part of https://github.com/epiforecasts/covid/issues/42.

**Comment by seabbs** [comment]
it would - investigating (clashes with use as pdf but can be worked around).

**Comment by gunnarkaestle** [comment]
I would keep the PDFs as a downloadable backup.

**Comment by seabbs** [comment]
done
