### ISSUE TITLE
some plot facets are too small to be legible

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid#40]
e.g., https://epiforecasts.io/covid/posts/national/united-states/

**Comment by gunnarkaestle** [comment]
If you click on the figure matrix and download it, you get the diagram in full resolution.
![2020-04-20_R-matrix_US](https://user-images.githubusercontent.com/15989715/79798077-b5e0f100-8358-11ea-992f-a2d5172f05fb.png)
