### ISSUE TITLE
Africa Countries: Kosovo classified to be In Africa

### ISSUE THREAD

**Issue by yuster0** [epiforecasts/covid#41]
Bringing to your attention that Kosovo is not in Africa, but in rather in Europe. Kindly rectify accordingly

**Comment by seabbs** [comment]
Thanks - do you have a suggestion about what might be causing this issue? We are using UN regions and linking to country names.

**Comment by yuster0** [comment]
Dear Sam,
I appreciate, perhaps  my guess could be a mix of classification of region
where Kosovo is lamp to africa region, and that require correction the
names in json file or shapefile.

*Yuster Ronoh* |  Mobile +254724305899/ +254733573770 | Skype: yronoh

**Comment by seabbs** [comment]
Right should be fixed in the version that has just gone live - let me know if this is not the case. Thanks for flagging.
