### ISSUE TITLE
Data for interactive maps and data visualisations

### ISSUE THREAD

**Issue by hamishgibbs** [epiforecasts/covid#42]
I have been working on interactive maps and data visualisations consulting with @seabbs. The vis are interactive svgs written with d3.js, and packaged as html widgets for inclusion in the .Rmd document. 

There is a sample vis [here](https://hamishgibbs.github.io/rt_interactive_vis/index.html).

Can I request 2 files to make this more straightforward and reliable?

`rt.csv` is working well to generate the r0 plot for each country. Could we have a similar file for the nowcasts and a summary file for country classifications? 

**For nowcasts:**

Proposed file columns:

`country` : country name - using the same country names as `rt.csv`
`date` : date
`median` : nowcast median
`lower_90` : nowcast lower 90% CI - currently named 'bottom'
`upper_90` : nowcast upper 90% CI - currently named 'top'
`lower_50` : nowcast lower 50% CI - currently named 'lower'
`upper_50` : nowcast upper 50% CI - currently named 'upper'
`cases` : number of cases on each date - all NA values set to 0

(assuming that the original columns are 50% and 90% CI's)

This would make the format of the new nowcast csv file the same as `rt.csv`. 

For individual country visualisations, these datasets could just be subset for each country and we could output static svgs with the same styles. 

**For summary map:**

Could we output a summary csv file of the classification of each country. 

Proposed file columns:

`country` : country name - using the same country names as `rt.csv` and the above file.
`trajectory` : with 6 coded values - `decreasing, likely_decreasing, unsure, increasing, likely_increasing, no_data`

This would allow for a quick join of the map data to each day's classification and then some styles.

Thanks, let me know what you think.

**Comment by sbfnk** [comment]
This looks nice! We'll probably still want a list somewhere, otherwise you'll never know Rt in Luxembourg.

**Comment by hamishgibbs** [comment]
Agreed @sbfnk. Russia dominates that map. 

Would you like a country selection dropdown or country search bar? 

Could also add pan & zoom functionality, or inset maps but those will take a bit more time.

**Comment by seabbs** [comment]
All of those things? (maybe not the insets)

**Comment by hamishgibbs** [comment]
Updated version of the visualisation [here](https://hamishgibbs.github.io/rt_interactive_vis/index.html). To do: 
- country selection
- pan and zoom of bottom plots
- remove median & change CI labelling

**Comment by gunnarkaestle** [comment]
The development for national R_t estimations are correctly shown, but the second figure with the case numbers is always the same.

**Comment by hamishgibbs** [comment]
The visualisation is a test and the second panel is using a dummy dataset. This issue is open in order to get data a more standard data format for the second panel.

**Comment by piccolbo** [comment]
Hi I am interested too in downloadable estimates. Please use a standard for country and state names (iso alpha 2 or 3, FIPS for US) or joining with other information will be a project, e.g. choropleths or cartograms. The guys at rt.live have downloadable csvs  and the twittersphere is abuzz (I hate my language) with different visualizations. Their numbers ... I am skeptical, but that's a different subject.

**Comment by hamishgibbs** [comment]
@sbfnk and @seabbs, there are new test visualisations with the feature additions you mentioned here: 
https://hamishgibbs.github.io/rt_interactive_vis/index.html

and here:
https://hamishgibbs.github.io/rt_interactive_vis/r0_compare.html

Please let me know how they look, what needs changing, and what next steps should be. I think making this compatible with regional estimates once the global map is stable.

**Comment by hamishgibbs** [comment]
Also for the r0 Country Comparison, I think the division by continent is perhaps unnecessary, and adds another step to the data processing. I think the countries could just be rearranged the way they are currently in the summary plot, then animated, retaining that order at each time step. Let me know what you think.

**Comment by seabbs** [comment]
Closing
