### ISSUE TITLE
Venezuela R=

### ISSUE THREAD

**Issue by VENEZUELA2017** [epiforecasts/covid#44]
Do you have information about R0 COVID-19 for Veenzuela?

**Comment by joeHickson** [comment]
Hi,
You can find the national summary (updated recently) here, based on global data sets: https://epiforecasts.io/covid/posts/global/
The raw data is published here (currently): https://github.com/epiforecasts/covid-global/tree/master/national/Venezuela/latest
A further breakdown of the figures within Venezuela is not yet available - if a data source is available do consider adding a ticket on the NCovUtils repo (or ideally a pull request) https://github.com/epiforecasts/NCoVUtils/issues  - once the data is available a PR can be added here to include it in the processing suite.
Sorry for the delay, hopefully you can find the figures you are looking for.

Joe
