### ISSUE TITLE
Brazil Data Latest Update

### ISSUE THREAD

**Issue by FilipeArcanjo** [epiforecasts/covid#45]
The page containing data for Brazil doesn't make it clear which estimates use data up to 2020-04-14 and which use data up to 2020-04-24. 

 https://epiforecasts.io/covid/posts/national/brazil/

**Comment by seabbs** [comment]
Hi @FilipeArcanjo 

Sorry for the confusion. All estimates use data up to the 24th. The other date (as mentioned on the page) is the date of infection for the estimates. As we are using reported cases this is lagged by the report delay (~ 4 days) and incubation period (~ 5 days) meaning that all estimates lag by around 9~10 days.
