### ISSUE TITLE
rate of growth, R^2

### ISSUE THREAD

**Issue by gunnarkaestle** [epiforecasts/covid#47]
Ref: https://epiforecasts.io/covid/posts/national/united-states/ Figure 3

First, the rate of growth should be properly defined. If the serial interval is assumed to be constant, then rate of growth and effective reproduction number is equal. So rate of growth needs a proper time frame, IIRC it is the _daily_ growth rate - in the beginning we had ~25% more infections each day.

I have not fully understood how the results of Fig. 3C on the coefficient of determination were calculated. Does it show an evaluation on A or B? The caption says "with values closer to 1 indicating a better fit", so I would doubt the whole calculation if R squared goes negative.

**Comment by PatParslow** [comment]
With https://epiforecasts.io/covid/posts/national/united-kingdom/ figure 3 also - R^2 being negative seems unlikely, unless complex numbers are involved.

**Comment by gunnarkaestle** [comment]
Maybe I should be more precise: if the serial interval is assumed to be constant, then the rate of growth r is a simple transformation from the reproductive number R_t: e^(ln(1+r))*t is the exponential growth formula and we need to now to which time frame the growth rate r refers to: Year? Month? Week? I assume, that it is the daily growth and this should be stated in the caption of figures 3A.

Regarding the problem with negative R squared, I think this has been solved by clipping the diagrams at 0.00 so there is no suggestion anymore that R squared is indeed negative, it is just a question of mathematically calculating confidence intervals which become rather wide when r goes through 0 (R_t through 1) and therefore the doubling time swaps the infinity sign. Nevertheless it should be emphasised that fig 3C refers to 3A and not 3B, which is a derivative of 3A.

**Comment by seabbs** [comment]
Good point - its the daily growth rate. Will open issue in [EpiNow2](https://epiforecasts.io/EpiNow2/) to fix.
