### ISSUE TITLE
Data for Germany

### ISSUE THREAD

**Issue by adhusch** [epiforecasts/covid#52]
Great work, thank you for providing this!

Could you please clarify which exact data source you are using for Germany?  The linked source https://github.com/jgehrcke/covid-19-germany-gae is providing official data from RKI as well as data "curated" by two large german newspapers. The newspaper source is always more recent but the quality of the curation is debatable. The data plotted at your tool today looks unreliable (seems to have a gap for the last days and looks in general inconsistent to the offical data). Maybe it would be worth considering switching to the official RKI data? Might even be an option to take RKI data augmenting it using other source for the last three days where RKI is lacking behind? Please see screenshots attached.

Thank you

"Your Data" (gap, weird jumps):
<img width="584" alt="Screenshot 2020-05-04 at 19 37 02" src="https://user-images.githubusercontent.com/27815260/80995525-a96f9480-8e3e-11ea-8587-4b10ef023ceb.png">
.
"Official Data" (dense, looking very consistent in general except for the weekend effect):
<img width="1084" alt="Screenshot 2020-05-04 at 19 36 37" src="https://user-images.githubusercontent.com/27815260/80995544-ad9bb200-8e3e-11ea-9f1b-8749642bbfa7.png">

**Comment by kathsherratt** [comment]
Hi @adhusch - thanks for the comment. We also noticed this problem and have now switched to using RKI data from the source. Unfortunately it took a while as we ran into quite a few other issues this week. German data should be up to date from tomorrow.

**Comment by adhusch** [comment]
Hi,

great that you're back online with recent data :-)

Unfortunatly the national level data for Germany still seems to origin from the mixed data source containing gaps and jumps yielding unreliable predictions. 

Best
Andy

**Comment by kathsherratt** [comment]
Hi Andy,

Thanks very much for spotting an error! As of my last comment, the data have been sourced from RKI directly. However we haven't yet updated the reference text on the German page. We are fixing this with the next update.

While there are no longer any gaps, agreed the data still look a little strange: even in the RKI data, there are some very low case counts (e.g. Mecklenburg-Vorpommern) with a strong weekly seasonality in reporting. There's nothing immediate we can do about this, but we are thinking about how to address it.

Kath

**Comment by adhusch** [comment]
Hi Kath,

thank a lot for looking into this so swiftly :-)

I am a bit confused now as you only refer to the "reference text". The data in the current national level plot is not from RKI (or there is a bug in the fetching processing inducing very weird things):

![data1](https://user-images.githubusercontent.com/27815260/82191848-6f4ccb00-98f3-11ea-97d5-bd743dcf500c.png)

The data on individual state level looks fine :-) Mecklenburg Vorpommern indeed has very low case numbers, essentially any model might more ore less solely fit to noise there in the end. I guess that's essentially a problem with any smaller country with very low absolute case numbers. On national level Luxembourg is another example. Unfortunatly in your model the R_t's and CI's are "pulled up" a lot then for the most recent data when these countries have a low R_t, i guess due to influence of a prior that is not realistic anymore for the current "R_t ~ 1" scenario in these countries?

Best
Andy

**Comment by seabbs** [comment]
Hi Andy, 

Thanks for exploring this in such detail - it's a great help. 

So the national estimates are all derived from the ECDC data source rather than summed using the regional data sources. This is so that national estimates are comparable but I agree it can cause some confusion when looking within a country and is perhaps something we should think about changing/flagging more clearly. 

It is a good point about the low case estimates (Iceland is also another example) and you are right in the assumption that the estimates are being pulled toward the prior. There are 3 options here as I see it: allow the prior to dominate and accept the estimates are highly uncertain as without case data Rt can't be known, allow the prior to dominate but assume a smaller more certain prior (i.e a R ~ 1 scenario) or make the model better able to handle low data scenarios. 

We are currently working on 3 but it is a hard problem as the issue comes from both how we upscale cases and estimate R. Updating the prior is an option but we are concerned that providing to much weight to a ~ 1 scenario may make movements away from this hard to detect. 

Sam

**Comment by adhusch** [comment]
Hi Sam, 

thanks a lot for the detailed explanations.

Could it be an option to make the prior dependent on the absolute number of cases (i.e. shrink the expected value of the prior towards one when new cases go towards zero, ideally non-linear in the sense that it attains the original value quickly again when new cases go up again)? Okay, from some perspective might is just a smooth way of saying "no model fit possible - to low numbers" and outputting NaN ;-)

Best
Andy

**Comment by jgehrcke** [comment]
> The linked source https://github.com/jgehrcke/covid-19-germany-gae is providing official data from RKI as well as data "curated" by two large german newspapers. The newspaper source is always more recent but the quality of the curation is debatable.

Hey! Only seeing this thread now. I am the person behind https://github.com/jgehrcke/covid-19-germany-gae :). Dropping a comment to say that I very much agree with this conclusion. After all these months it becomes more and more apparent how important it is to consider RKI/ArcGIS-provided time series data _if_ you're doing time series analysis -- the RKI data set sees significant amendments far into the past, especially for the time series reflecting deaths.

That is, if you are (still) using https://github.com/jgehrcke/covid-19-germany-gae -- I strongly recommend consuming the `-rki-*csv` files.
