### ISSUE TITLE
Duplicate "Figure 1" in global summary

### ISSUE THREAD

**Issue by sanxiyn** [epiforecasts/covid#53]
In [Covid-19: Global summary](https://epiforecasts.io/covid/posts/global/), figures are misnumbered. There are two "Figure 1" figures.

**Comment by joeHickson** [comment]
I think this might be to do with this line here:
https://github.com/epiforecasts/covid/blob/47add0429d2162947eeae35764079b8164a95abd/_posts/global/global.Rmd#L56

It seems to insert a Figure 1 before pulling in a template report. It seems the template report can be told it is not running in standalone mode and be told what number to start from. It might be resolvable with something like this (but I need to test it):
`standalone <- FALSE
fig_start <- 2
tab_start <- 1`

**Comment by seabbs** [comment]
Good spot. Yes, that is how it works. Its a little clunky as it means the global variables rely on global variables.

**Comment by seabbs** [comment]
Should now be fixed - thanks again.
