### ISSUE TITLE
Reported doubling times in table have strange intervals

### ISSUE THREAD

**Issue by samclifford** [epiforecasts/covid#55]
At the time of writing, Table 1 on https://epiforecasts.io/covid/posts/global/ has some bizarre entries, such as Australia's doubling time of -71 (7 – -6), or Austria's of 440 (15 – -16). Belgium has -14 (-22 – -10), which indicates the issue might be the way doubling/halving times are reported back to the table when the interval contains 0.

Cameroon is 110 (15 – -21) and the estimate is not contained within the interval at all. Same with Cote d'Ivoire, 51 (9.7 – -16). Croatia is -10 (15 – -3.8). Bahrain is 200 (17 – -20). These are reflected in the national summaries, e.g. https://epiforecasts.io/covid/posts/national/cameroon/ and it's clear that there's something wrong when converting from growth rates to doubling/halving times.

**Comment by samclifford** [comment]
The crux of the issue there is that the doubling time is calculated from the growth parameter and when this is 0 the doubling time is infinite, and when the growth parameter is close to 0 the doubling time tends towards a signed infinity based on the sign of the growth parameter.

To fix the plotting, a daily overplotted linerange (similar to Figure 1 [here](https://epiforecasts.io/covid/posts/global/) could replace the ribbon visualisation of time-varying doubling time.

To fix the reporting of doubling time in the table, the mean should be replaced by the median as it's guaranteed to be within the 90% interval and for most settings the mean and median will be similar. Also the doubling time is calculated [after](https://github.com/epiforecasts/EpiNow/blob/ab4e39bf9facb5394dcbdc4411ae2162553c85eb/R/estimate_littler.R#L114) the [summary statistics](https://github.com/epiforecasts/EpiNow/blob/ab4e39bf9facb5394dcbdc4411ae2162553c85eb/R/estimate_littler.R#L107) which is fine for quantiles but not moments. So perhaps the mean ought to be calculated separately and cbinded on.

**Comment by hutchenm** [comment]
The error occurs in doubling time data in all rows in which there is a negative in the credible interval, as observed today (7/2) at https://epiforecasts.io/covid/posts/national/united-states/.  If one terminus of the credible interval is <0, then the reported mean value falls very far outside the reported credible interval.  It's possible for a mean value to fall outside the credible interval, but it seems very unlikely this would only occur with negative credible termini, and it seems unlikely it would always be so far outside the range.  Replacing with median might correct a data presentation problem, but I am suspicious there is an  underlying assumption problem.

**Comment by seabbs** [comment]
Hi @hutchenm , 

Thanks for flagging this. As the doubling time is an inversion of the growth rate as the growth rate approaches 0 the doubling time approaches infinity. Then when the growth rate cross 0 the doubling time becomes -Inf and then decreases. This means that the CI should be understood as going via Inf and not through 0.

**Comment by hutchenm** [comment]
Aha, I get it - the center of the interval is infinity.  There might be a way to notate that in the chart, as it's an unusual way to have an interval presented in medical data science.  Or maybe what you are doing is just standard and I should learn.

**Comment by gunnarkaestle** [comment]
Diagrams on doubling time look very scrambled when the country moves around R_t=1, meaning if there is a frequent crossing above and below 1 that results in vertical bars when the doubling time jumps from pos. infinity to neg. infinity and back. These graphical elements give no extra content to the reader, but only distract from the important facts. Therefore my proposal is (hopefully not too complex to implement) not to display these vertical bars and filter the R_t = 1 crossings out from the doubling time diagram. Doubling times of e.g. more than two months are not interesting, as the usual range which is shown is +-40 days.

**Comment by seabbs** [comment]
Good discussion on this. We are moving to an updated approach an no longer report the doubling time over time so closing this.
