### ISSUE TITLE
Why are nowcasts for the last few days always overestimated?

### ISSUE THREAD

**Issue by lucaventurini** [epiforecasts/covid#67]
Hello!

First of all, thanks a lot for all your work and your efforts in keeping this project up-to-date.

I have been following the Italian estimation for Rt for more than a month now, and I have noticed that the plot for Rt tends to be always rising in the few last days. But when you check back after a while for the same date, you see that it didn't increase after all (phew!😅)

See for example the estimate for the 12/04: seen on the 22, it seemed to be rising and getting very close to 1, but then it seems it didn't if you check again on 6/5. Again, check 25/4 (as seen on 6/5): seems very close to 1, but then it didn't if you check again on 22/5 (I took these 3 plots as they were saved on the Web Archive).

22/04:
![image](https://user-images.githubusercontent.com/2151065/82670989-6aaf4c00-9c3e-11ea-8aec-eec871c337dd.png)

06/05:
![image](https://user-images.githubusercontent.com/2151065/82671070-861a5700-9c3e-11ea-9c54-a09f2a5e2c8c.png)

22/05:
![image](https://user-images.githubusercontent.com/2151065/82671106-929eaf80-9c3e-11ea-9189-e8da90970e8f.png)

Now, my question, maybe to @seabbs ,is whether there is some space for improvements here. I understand that the last days are more prone to errors, but it seems that the model has some "bias" to favor "pessimistic" views which is quite consistent during time, so maybe it's something that could be taken into account.

But again, many kudos for all the work, keep up with it!

**Comment by MohammedAlrozzi** [comment]
I am not an expert in this but I have similar observation. I think if new cases are only 200, and the day after where 220, the Rt will be more 1. The Rt, as I understood it, does not reflect the seriousness of the situation as much it reflects a form of stability or being under control. You may have two countries (A) increasing 4000 cases every day and (B) increasing 300 cases everyday, the Rt will be similar, and certainty will be determined of many cases, and the trend of increase in each of the reported countries. I would like to hear more on this from the experts.

stay safe,
mohammed

**Comment by gunnarkaestle** [comment]
I agree that the R_t value is a "stability parameter" (in electrotechnical engineering that is similar to damping, meaning R_t smaller than 1 or in nuclear engineering it is criticality) and the absolute number of new cases is a different measurement (size of the problem vs. problem dynamics). When case numbers go down, the uncertainty of observing the infection dynamics (R_t) goes up.

**Comment by seabbs** [comment]
Thanks for this discussion, 

We have just switched to a new approach that should more robust near real-time estimates.
