### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid#7]
Some minor and non-critical comments:

Global summary page:
- [x] General: use of word “regions” > personal preference is the word “countries” instead as regions sounds more like a group of countries (but only a preference, either works)
- [x] Figure 1: “Likely Increasing” colour grey > looks a bit too close to NA to me - could change to e.g. light blue - or to a sequential scale so that all three values are in colour order (Increasing > Likely increasing > Unsure)
- [x] Figure 4: it might be easier to read and compare if ordered by geographic region, but not a problem as is
- [x] Figure 8: to me the title reads a bit awkwardly and doesn’t intuitively match the caption (which explains really well). Going by the caption, I’d change from “Cases with date of onset on the day of report generation in all regions” to “Cases by date of report, and estimated cases by date of infection”

Methods page:
- [x] Typo in header caption: “publically” > “publicly” available data

**Comment by seabbs** [comment]
All sounds good - light edit to add tick boxes

**Comment by seabbs** [comment]
Had a go at fixing figure 8 title - let me know what you think?

Think reordering by geography might be a bit of a mission. If keen on this please add to medium term changes as could be a good idea.

**Comment by seabbs** [comment]
Closed as resolved or categorized for future work
