### ISSUE TITLE
dates not updating properly

### ISSUE THREAD

**Issue by maia** [epiforecasts/covid#70]
On national pages such as https://epiforecasts.io/covid/posts/national/austria/ the title of the first h2 is "Summary (estimates as of the 2020-05-13)" even though the same page features the note "Using data available up to the: 2020-05-26". 

Also the description of Figure 1 and 2 both feature "Estimates from existing data are shown up to the 2020-05-13 from when forecasts are shown." which should probably update with the proper date too.

**Comment by seabbs** [comment]
Hi @maia, 

Thanks for flagging this. All estimates are shown by date of infection and are therefore lagged by about two weeks behind the data on which they are based. This means that using the latest data we can provide estimates for the 13th in Austria. Estimates from the 13th onwards are then forecasts. 

We state this at the top of the page but are very keen to hear how we can make this clearer: 

*"Note that it takes time for infection to cause symptoms, to get tested for SARS-CoV-2 infection, for a positive test to return and ultimately to enter the case data presented here. In other words, today’s case data are only informative of new infections about two weeks ago. This is reflected in the plots below, which are by date of infection."*

**Comment by maia** [comment]
Oh, thanks for the explanation. I'm not a native speaker, I would have interpreted "estimates as of …" as an estimate that was made on that date. To me it'd be clearer if it would say "Summary (estimates as of 14 days prior to the [date_of_latest_data])".

By the way, countries might have different speeds in testing, do you plan to adjust for that? (As for Austria, current cases are so low that for each positive test ~150 other people are tested, meaning that clusters are quickly identified, including a-/pre-symptomatic cases, so I would assume that the delay currently is shorter than in e.g. Brazil which most likely currently doesn't have the capacity to test all symptomatic cases.
