### ISSUE TITLE
Negative binomial in the Methods section

### ISSUE THREAD

**Issue by aakhmetz** [epiforecasts/covid#73]
Thank you for your work!

Just noticing that the notations o^* and of the subindex k were not really explained in the methods section when you defined the Negative binomial

https://epiforecasts.io/covid/methods.html

**Comment by jhellewell14** [comment]
Hello,

There is a more detailed explanation of the methods in [the paper](https://wellcomeopenresearch.org/articles/5-112), we are trying to move the methods section off the website and point to the paper instead :)
