### ISSUE TITLE
Credible intervals

### ISSUE THREAD

**Issue by BvdM0** [epiforecasts/covid#80]
Hi,

Is it possible to calculate, from the data provided by the regional_rt_pipeline, the smallest credible interval which excludes r=1? 

I would like to calculate this in order to be able to report a probability that r is above or below 1 for a given region on a particular day. However, I couldn't work out how to replicate the calculations of the 50% and 90% credible intervals.

Thank you

**Comment by jhellewell14** [comment]
Hello, 
Off the top of my head, would an approximation for this be to take the samples of R on the date of interest and then do 
(number of samples where R > 1) / (number of samples)

Is this what you were thinking of?

Cheers,
Joel

**Comment by BvdM0** [comment]
Hey, thanks for getting back to me. 

I think the solution was hiding in plain sight, but would like to check with you because I'm not totally sure: Is 'prob_control' in time_varying_params.RDS what I'm looking for?

**Comment by seabbs** [comment]
Hi Ben, 

Yes, that is correct. Just to note we will be transitioning the website estimations to a new approach (https://github.com/epiforecasts/EpiNow2) with a different data structure in the next few days. I will ping this issue when we do with the new location for this.


Sam
