### ISSUE TITLE
Global coronavirus data refresh?

### ISSUE THREAD

**Issue by akchandarana** [epiforecasts/covid#81]
Towards the bottom of this page just above the table of global data: https://epiforecasts.io/covid/posts/global/
The date in the following message hasn't changed in over a week.
     "Latest estimates (as of the 2020-06-26) - Table 1: Latest estimates (as of the 2020-06-26) of the number of confirmed cases by date of infection, the effective reproduction number, and the doubling time..."

Curious if updates will continue?

**Comment by joeHickson** [comment]
Hi @akchandarana,
We're currently experience some technical difficulties but we are trying to resolve them and hope to have updates soon. In the meantime we are trying to get the results we can process through - you can check for the latest commits here on the global dataset:
https://github.com/epiforecasts/covid-global

Sorry for the inconvenience - we are very aware of the global demand for this information and we are working to achieve regular results.

**Comment by akchandarana** [comment]
@joeHickson - Thanks to you and the rest of the team pulling all this data together!  If I missed/didn't realize where to look for any updates/status on the global data, it's because I'm a github newbie and just pulling the summarized data directly from the table on https://epiforecasts.io/covid/posts/global/
I was mostly hoping to confirm that the project/data wasn't going away - thanks again!

**Comment by joeHickson** [comment]
The website should be receiving the updated data but it may be intermittent whilst we're sorting these issues. Sorry for the inconvenience.
