### ISSUE TITLE
colour scheme for mapping

### ISSUE THREAD

**Issue by gunnarkaestle** [epiforecasts/covid#82]
Here is another suggestion for a small improvement, which hopefully is easy to implement. In the global and national maps, the order of the different growth rates is as follows:
- increasing (red)
- likely increasing (orange)
- unsure (dark grey)
- likely decreasing (light blue)
- decreasing (dark blue)

Some countries or subnational divisions are marked in light grey if there is no data available or not enough data. 

I'd like to suggest to swap dark (unsure) and light grey (no data), then the colour spectrum will fit better to the 5 stages. Light grey for "unsure" has a similar brightness as orange and light blue, so the eye can easily and more intuitively sort the growth rate "unsure (if up or down)" between "probably up" and "probably down". So far, the dark grey puts the "unsure" areas optically rather next to the ends of the spectrum  (de- & increasing) which use more intense colours with a lower brightness.

**Comment by joeHickson** [comment]
It's worth throwing any potential colour scheme through accessibility tools to check contrast and also confirm if it works with the more common forms of colour blindness.

**Comment by gunnarkaestle** [comment]
As you can see on the map of Africa, Asia and Europe, the "stable" grey is quite intensive, and has a lower lightness than the adjacent light orange (lightly increasing) and light blue (likely decreasing). I'd like to propose to change the L value slightly to a light grey, so that the Stable areas will not be mistaken as dark orange or blue (increasing/decreasing). 

The "no data" grey is almost white and can stay where it is, as the distance in the CIELAB colour space is large enough to the other colours in the legend.

![2021-04-27 R-value global estimates](https://user-images.githubusercontent.com/15989715/116293629-65844680-a797-11eb-922d-c205e91965b1.png)
