### ISSUE TITLE
threshold for case numbers

### ISSUE THREAD

**Issue by gunnarkaestle** [epiforecasts/covid#83]
Dear all, I like your work very much and I regularly check the results of the state estimation. If I had a free large wish from a genie, I would ask for some kind of math magic that allows to lower the threshold for the minimum case numbers, with which the estimator still delivers half-reasonable numbers.

In the end, policymakers at local level (e.g. per county) need to implement some degrowth measures - this should be done quickly to avoid putting a whole country into lockdown to avoid a second wave. "Control rods" need to be put into the large COVID reactor to avoid that the chain reaction is speeding up. One signal is the easy to measure new registered cases (see attached activity maps as example: new infections of the last 7 days per 100.000 inhabitants in DE). But a second set of warning lights could be helpful as well, which show growth indicators in addition to the activity level. In electrical power engineering we look both at the frequency and the ROCOF (rate of change of frequency), therefore it is logical for me to look also at the absolute level of new infections and the rate of change of new infections (ROCONI). 

![2020-04-10 COVID activity in DE](https://user-images.githubusercontent.com/15989715/88139381-ddfa1d80-cbef-11ea-84bc-a121aad02e2f.png)
![2020-07-22 COVID activity in DE](https://user-images.githubusercontent.com/15989715/88139394-e2263b00-cbef-11ea-98fe-872c24fe6b9b.png)

I am aware that this needs some really tricky filtering and may result in nonsense results as super-spreading events are singular and seldom but will falsify the general view how community spreading does evolve. Nevertheless, it would be a helpful tool even with some big caveat warnings.

**Comment by seabbs** [comment]
Hi @gunnarkaestle, 

Thanks for this and sorry for the slow reply. 

We are just in the process of updating to a new method that is more robust at low case counts so this should be possible. In general, we are interested at looking at lower level estimates but it is not currently something we have been able to explore.
