### ISSUE TITLE
Ireland and China Rt Values

### ISSUE THREAD

**Issue by GSOCBiogen** [epiforecasts/covid#86]
Hello, both the Irish and Chinese Rt values (which were previously reported and still appear on the global page) are no longer available in the "Asia" or "Europe" tabs. Will they be coming back? 

https://epiforecasts.io/covid/reports.html#Asia
https://epiforecasts.io/covid/reports.html#Europe

**Comment by seabbs** [comment]
Thanks for this and sorry for the delayed response. 

We have just switched to a new approach so these should be again available.
