### ISSUE TITLE
Missing resources on landing page?

### ISSUE THREAD

**Issue by bjda** [epiforecasts/covid#89]
The page at https://epiforecasts.io/covid appears blank, and log indicates missing resources.

Screenshot: ![Capture4](https://user-images.githubusercontent.com/51139291/91637535-81b5c500-ea09-11ea-98dd-e82df0c1f611.PNG)

**Comment by seabbs** [comment]
Thanks for flagging this.

Should now be fixed (site libs were accidentally added to the gitignore).
