### ISSUE TITLE
Mapping UK

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid#90]
New interface with `RtD3` works well apart from in the UK. Shapefiles are mostly a closed book to me so any ideas appreciated. May be partially fixed by upstream work on `RtD3` to making linking easier. Any ideas @kathsherratt  or @hamishgibbs?

**Comment by hamishgibbs** [comment]
If data is coming in NHS regions, not Local Authorities, you will need a custom shapefile of those regions in order for the map and plots to play together correctly. I am not familiar with your pipeline so not sure how challenging it is to add custom geodata. 

Something else that I have found working with NHS regions  is that they change often so important to make sure that that we use the correct shapefile (RtD3 should warn about name issues).

**Comment by seabbs** [comment]
Yes all good points. @kathsherratt built one out that worked well but for unknown reasons I couldn't link it with `RtD3` when we rolled that out. I'll have a look around and try and work out what the problem was (🤓 ).

**Comment by seabbs** [comment]
Mapping temporarily removed from the site due to instability issues.
